services:
  producer:
    build: producer-end
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8083
    depends_on:
      rabbitmq:
        condition: service_healthy

  company-a:
    build: company-a
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8084
    depends_on:
      rabbitmq:
        condition: service_healthy

  company-b:
    build: company-b
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8085
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:latest
    mem_limit: 512m
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 2s
      retries: 60
