server.port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: orders-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.baeldung.ls.common.OrderDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.baeldung.ls.common.OrderSerializer


spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings:
    message-out-0:
      destination: messages