server.port: 8086

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: matches-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.baeldung.ls.common.MatchDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.baeldung.ls.common.MatchSerializer
      acks: all


spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings:
    message-out-0:
      destination: messages